### PR TITLE
Update how we preprocess Fortran files

### PR DESCRIPTION
**Pull request by amontoison**
@nimgould 
I updated the main `meson.build` such that the preprocessed files have the extension `.f90` and I don't use anymore the `-cpp` / `-fpp` flag when I compile them.
It fixed the errors with `nagfor` and removed the warnings "bad # preprocessor line" with `ifort`.

However, I have this new error with the NAG compiler:
```shell
FAILED: libgalahad_single.so.p/meson-generated_single_contrib.f90.o 

libgalahad_single.so.p/spral_ssids_contrib_single.mod 
nagfor -Ilibgalahad_single.so.p -I. -I.. -Iinclude -I../include -I../src/dum/include -Isrc/ampl -I../src/ampl -quiet -w=all -O0 -g -dcfuns -Dmetis_nodend=galahad_metis -PIC -DSPRAL_NO_SCHED_GETCPU -DSPRAL_HAVE_HWLOC -DGALAHAD_SINGLE -DSPRAL_SINGLE -mdir libgalahad_single.so.p -o libgalahad_single.so.p/meson-generated_single_contrib.f90.o -c libgalahad_single.so.p/single_contrib.f90
../src/ssids/contrib.F90: In function ‘spral_ssids_contrib_get_data_single’:
../src/ssids/contrib.F90:60:66: error: lvalue required as left operand of assignment
   60 |      call c_f_pointer(ccontrib, fcontrib)
      |  
```

I also observed that I need to compile the C++ files of `ssids` with `-qopenmp` when I use the `icpc` compiler but I have a bunch of errors of the form:
```shell
../src/ssids/ldlt_app.cxx(1944): warning #3850: cancellation point with no cancel in region
                     #pragma omp cancellation point taskgroup
                     ^
          detected during:
            instantiation of "int spral::ssids::cpu::ldlt_app_internal_sgl::LDLT<T, BLOCK_SIZE, Backup, use_tasks, debug, Allocator>::run_elim_unpivoted(int, int, int *, T *, int, T *, spral::ssids::cpu::ldlt_app_internal_sgl::ColumnData<T, spral::ssids::cpu::ldlt_app_internal_sgl::LDLT<T, BLOCK_SIZE, Backup, use_tasks, debug, Allocator>::IntAlloc> &, Backup &, int *, const spral::ssids::cpu::cpu_factor_options &, int, T, T *, int, std::vector<spral::ssids::cpu::Workspace,
                      std::allocator<spral::ssids::cpu::Workspace>> &, const Allocator &) [with T=float, BLOCK_SIZE=32, Backup=spral::ssids::cpu::ldlt_app_internal_sgl::CopyBackup<float, spral::ssids::cpu::BuddyAllocator<float, std::allocator<float>>>, use_tasks=false, debug=false, Allocator=spral::ssids::cpu::BuddyAllocator<float, std::allocator<float>>]" at line 2350
            instantiation of "int spral::ssids::cpu::ldlt_app_internal_sgl::LDLT<T, BLOCK_SIZE, Backup, use_tasks, debug, Allocator>::factor(int, int, int *, T *, int, T *, Backup &, const spral::ssids::cpu::cpu_factor_options &, spral::ssids::cpu::PivotMethod, int, T, T *, int, std::vector<spral::ssids::cpu::Workspace, std::allocator<spral::ssids::cpu::Workspace>> &, const Allocator &) [with T=float, BLOCK_SIZE=32, Backup=spral::ssids::cpu::ldlt_app_internal_sgl::CopyBackup<float,
                      spral::ssids::cpu::BuddyAllocator<float, std::allocator<float>>>, use_tasks=false, debug=false, Allocator=spral::ssids::cpu::BuddyAllocator<float, std::allocator<float>>]" at line 999
            instantiation of "int spral::ssids::cpu::ldlt_app_internal_sgl::Block<T, INNER_BLOCK_SIZE, IntAlloc>::factor(int, int *, T *, const spral::ssids::cpu::cpu_factor_options &, std::vector<spral::ssids::cpu::Workspace, std::allocator<spral::ssids::cpu::Workspace>> &, const Allocator &) [with T=float, INNER_BLOCK_SIZE=32, IntAlloc=std::__alloc_rebind<spral::ssids::cpu::BuddyAllocator<float, std::allocator<float>>, int>, Allocator=spral::ssids::cpu::BuddyAllocator<float,
                      std::allocator<float>>]" at line 1812
            instantiation of "int spral::ssids::cpu::ldlt_app_internal_sgl::LDLT<T, BLOCK_SIZE, Backup, use_tasks, debug, Allocator>::run_elim_unpivoted(int, int, int *, T *, int, T *, spral::ssids::cpu::ldlt_app_internal_sgl::ColumnData<T, spral::ssids::cpu::ldlt_app_internal_sgl::LDLT<T, BLOCK_SIZE, Backup, use_tasks, debug, Allocator>::IntAlloc> &, Backup &, int *, const spral::ssids::cpu::cpu_factor_options &, int, T, T *, int, std::vector<spral::ssids::cpu::Workspace,
                      std::allocator<spral::ssids::cpu::Workspace>> &, const Allocator &) [with T=float, BLOCK_SIZE=32, Backup=spral::ssids::cpu::ldlt_app_internal_sgl::CopyBackup<float, spral::ssids::cpu::BuddyAllocator<float, std::allocator<float>>>, use_tasks=true, debug=false, Allocator=spral::ssids::cpu::BuddyAllocator<float, std::allocator<float>>]" at line 2350
            instantiation of "int spral::ssids::cpu::ldlt_app_internal_sgl::LDLT<T, BLOCK_SIZE, Backup, use_tasks, debug, Allocator>::factor(int, int, int *, T *, int, T *, Backup &, const spral::ssids::cpu::cpu_factor_options &, spral::ssids::cpu::PivotMethod, int, T, T *, int, std::vector<spral::ssids::cpu::Workspace, std::allocator<spral::ssids::cpu::Workspace>> &, const Allocator &) [with T=float, BLOCK_SIZE=32, Backup=spral::ssids::cpu::ldlt_app_internal_sgl::CopyBackup<float,
                      spral::ssids::cpu::BuddyAllocator<float, std::allocator<float>>>, use_tasks=true, debug=false, Allocator=spral::ssids::cpu::BuddyAllocator<float, std::allocator<float>>]" at line 2563
            instantiation of "int spral::ssids::cpu::ldlt_app_factor_sgl(int, int, int *, T *, int, T *, T, T *, int, const spral::ssids::cpu::cpu_factor_options &, std::vector<spral::ssids::cpu::Workspace, std::allocator<spral::ssids::cpu::Workspace>> &, const Allocator &) [with T=float, Allocator=spral::ssids::cpu::BuddyAllocator<float, std::allocator<float>>]" at line 2571
```
It works if we can compile without `-qopenmp` like we currently do in our CI builds but the code is sequential.

### CODE REVIEW

**Comment by amontoison** [comment]
@nimgould Do you also have the error with the routine `c_f_pointer` when you compile with the `nagfor` compiler? I forgot to recontact you about it but I only have a license for one month.

**Comment by nimgould** [comment]
Yes, but as nagfor doesn't support openmp, we use the dummy version of ssids in this case

**Comment by nimgould** [comment]
(I'll see if I can fix this issue, it will be a wrong c or fortran type in some component)

**Comment by amontoison** [comment]
> Yes, but as nagfor doesn't support openmp, we use the dummy version of ssids in this case

What is the goal of the `-openmp` that we can use with nagfor if it doesn't support OpenMP?

**Pull request merged**
