### PR TITLE
Rename files prior to work on header file multiprocession provision

### PR DESCRIPTION
**Pull request by nimgould**
Working on multiple precision, this will take months, so no action needed as yet!

### CODE REVIEW

**Comment by amontoison** [comment]
Nick, you did a small mistake with this branch (`multi-precision`), you rebased it against the `meson-build` branch.
You mixed the two branches and we want to avoid that.
To fix the problem, you need the following command:
`git rebase -i 45cbff08644b17ccf204704320a7546cd5710bfe`
Capture d’écran du 2023-02-05 22-09-50
and write `drop` instead of `pick` near the commits that you want to remove.

`45cbff08644b17ccf204704320a7546cd5710bfe` is the SHA (commit ID) of last commit before our commits for Meson.
 
After we have a few conflicts to fix:
Capture d’écran du 2023-02-05 22-16-03
To fix them you need to go inside each file with conflicts and decide what you want to keep. For example, we have the following conflict in `src/general/makemaster`:
```
<<<<<<< HEAD
	cd $(OBJ); $(FORTRAN) -o ssids.o $(FFLAGS) ssids.F90
=======
	cd $(OBJ); $(FORTRAN) -o ssidd.o $(FFLAGS) ssids.F90
>>>>>>> 9b4b11bd (correction to stop multiple ssids copies in compiled library)
```
When the conflicts are fixed:
```shell
git add file1_with_conflits
...
git add fileN_with_conflits
git rebase --continue
```
At the end you will need a `git push -f` to push the modifications.

Don't worry, I did a backup of this branch ( branch `multi-precision-backup`).

**Comment by nimgould** [comment]
Sorry for the mess, I really don't understand all of this, but am happy to do what you want. 

I got as far as the drops, the edits to the conflicts and the git adds. Then when I 

% git rebase --continue
[detached HEAD a7e30978] correction to stop multiple ssids copies in compiled library type updates and other corrections to various test programs
 Author: Nick Gould <dalekopera@gmail.com>
 3 files changed, 132 insertions(+), 133 deletions(-)
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git rebase --skip'
interactive rebase in progress; onto 45cbff08
Last commands done (55 commands done):
   pick 9b4b11bd correction to stop multiple ssids copies in compiled library type updates and other corrections to various test programs
   pick 40ae24f9 Fix arcti.F90
  (see more in file .git/rebase-merge/done)
Next commands to do (24 remaining commands):
   pick 51780119 similar fix for arcs4
   pick 7fbc459f Fix llstt test
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'multi-precision' on '45cbff08'.
  (all conflicts fixed: run "git rebase --continue")

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	include/galahad_single.h_old
	man/index.db
	src/general/old_makemaster_basic
	src/ugo/ugocds.output
	src/ugo/ugocs.output
	src/ugo/ugodt.output
	src/ugo/ugos.output
	src/ugo/ugos3.f90~
	src/ugo/ugost.output

nothing added to commit but untracked files present (use "git add" to track)
Could not apply 40ae24f9... Fix arcti.F90

What does this mean? If I try 

% git push -f 
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)

Have I broken everything?

**Comment by nimgould** [comment]
OK, it seems that I have to keep applying git rebase --continue for as many times as necessary, fixing broken merges along the way. Let's see ...

**Comment by amontoison** [comment]
> OK, it seems that I have to keep applying git rebase --continue for as many times as necessary, fixing broken merges along the way. Let's see ...

🤞

**Comment by nimgould** [comment]
This is terrible, I am having to edit hundreds of files ...

**Comment by amontoison** [comment]
OK Nick, let's stop the process. I propose to merge the pull request like this. Is it fine for you?

**Comment by nimgould** [comment]
OK, I have now edited everything and pushed. I'm just recompiling to see if I didn't make a mistake, quite likely I suspect

**Comment by nimgould** [comment]
It now seems ok, so no need to merge the pull request

**Comment by amontoison** [comment]
> It now seems ok, so no need to merge the pull request

I checked too and everything is ok.
Fantastique Nick!

**Comment by amontoison** [comment]
Nick, you broke again the branch.
I suppose that you are at home today and you used a `git pull` instead of a `git rebase origin/multi-precision`.
You overwrite the history of the commits yesterday, so `git rebase` is mandatory.

**Comment by nimgould** [comment]
Sorry, Alexis, I really don't know what I am doing, do I? I presume that I am already on multiprecision at home, so why didn't it work?

When I tried the rebase, I was told that I had changes that I should "stash" (whatever that means), so I moved my recent changes, and tried another rebase, and that failed with the same error,  
error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.

As I have been working on the changed files all morning, I don't want to lose them.

**Comment by nimgould** [comment]
I have now git commit -a / push , and at least the rebase now doesn't complain. But I honestly don't know if that restored things

**Pull request closed without merging**
