### PR TITLE
Update BLAS -- version 3.11.0

### PR DESCRIPTION
**Pull request by amontoison**
Nick, I created a new folder `src/blas` with the last release of reference BLAS.
I didn't removed `blas_interface.F90` and `blas.f` in `src/lapack` such that I don't break your build system.
We will use the last version of BLAS routines in the CI tests, It could solve some errors.

Maybe we could merge the source files of reference BLAS with `cat` such that we only have to store `blas1.f` and `blas2.f90`?

The current `meson.build` in `src/blas` is
```meson
libgalahad_src += files('blas_interface.F90')

if not libblas.found()
  warning('building the reference BLAS version 3.11.0; consider providing an optimized BLAS library')
  libgalahad_src += files('cgemv.f', 'cher2k.f', 'cscal.f', 'ctbmv.f', 'ctrsv.f',
                          'dgemm.f', 'drotmg.f', 'dswap.f', 'dtbmv.f', 'dtrsv.f',
                          'lsame.f', 'scopy.f', 'snrm2.f90', 'sspmv.f', 'ssyr2k.f',
                          'strmm.f', 'zcopy.f', 'zgemv.f', 'zher2k.f', 'zscal.f', 'ztpmv.f',
                          'caxpy.f', 'cgerc.f', 'cher.f', 'csrot.f', 'ctbsv.f', 'dasum.f',
                          'dgemv.f', 'dsbmv.f', 'dsymm.f', 'dtbsv.f', 'dzasum.f', 'sdot.f',
                          'srot.f', 'sspr2.f', 'ssyr.f', 'strmv.f', 'zdotc.f', 'zgerc.f', 'zher.f',
                          'zswap.f', 'ztpsv.f', 'ccopy.f', 'cgeru.f', 'cherk.f', 'csscal.f', 'ctpmv.f',
                          'daxpy.f', 'dger.f', 'dscal.f', 'dsymv.f', 'dtpmv.f', 'dznrm2.f90', 'sasum.f',
                          'sdsdot.f', 'srotg.f90', 'sspr.f', 'ssyrk.f', 'strsm.f', 'zdotu.f', 'zgeru.f',
                          'zherk.f', 'zsymm.f', 'ztrmm.f', 'cdotc.f', 'chbmv.f', 'chpmv.f', 'cswap.f',
                          'ctpsv.f', 'dcabs1.f', 'dnrm2.f90', 'dsdot.f', 'dsyr2.f', 'dtpsv.f', 'icamax.f',
                          'saxpy.f', 'sgbmv.f', 'srotm.f', 'sswap.f', 'stbmv.f', 'strsv.f', 'zdrot.f',
                          'zhbmv.f', 'zhpmv.f', 'zsyr2k.f', 'ztrmv.f', 'cdotu.f', 'chemm.f', 'chpr2.f',
                          'csymm.f', 'ctrmm.f', 'dcopy.f', 'drot.f', 'dspmv.f', 'dsyr2k.f', 'dtrmm.f',
                          'idamax.f', 'scabs1.f', 'sgemm.f', 'srotmg.f', 'ssymm.f', 'stbsv.f',
                          'xerbla_array.f', 'zdscal.f', 'zhemm.f', 'zhpr2.f', 'zsyrk.f', 'ztrsm.f',
                          'cgbmv.f', 'chemv.f', 'chpr.f', 'csyr2k.f', 'ctrmv.f', 'ddot.f', 'drotg.f90',
                          'dspr2.f', 'dsyr.f', 'dtrmv.f', 'isamax.f', 'scasum.f', 'sgemv.f', 'ssbmv.f',
                          'ssymv.f', 'stpmv.f', 'xerbla.f', 'zgbmv.f', 'zhemv.f', 'zhpr.f', 'ztbmv.f',
                          'ztrsv.f', 'cgemm.f', 'cher2.f', 'crotg.f90', 'csyrk.f', 'ctrsm.f', 'dgbmv.f',
                          'drotm.f', 'dspr.f', 'dsyrk.f', 'dtrsm.f', 'izamax.f', 'scnrm2.f90', 'sger.f',
                          'sscal.f', 'ssyr2.f', 'stpsv.f', 'zaxpy.f', 'zgemm.f', 'zher2.f', 'zrotg.f90',
                          'ztbsv.f')
endif
```

### CODE REVIEW

**Comment by nimgould** [comment]
OK, but many of these are not needed. Perhaps what would be better is to replace the blas.f file with one that has a whole bunch of fortran include lines that pull in the relevant blas. I doubt that the blas have really been improved much.

Do you do the same for lapack?

Also, perhaps these should really be in the external directory?

**Comment by amontoison** [comment]
> OK, but many of these are not needed. Perhaps what would be better is to replace the blas.f file with one that has a whole bunch of fortran include lines that pull in the relevant blas. I doubt that the blas have really been improved much.

Indeeed, we should use Fortran include lines to only compile what we need.
In terms of performance, BLAS was not improved a lot but they improved the support of different architectures.

> Do you do the same for lapack?

I wanted your review before that I open another PR for LAPACK.

> Also, perhaps these should really be in the external directory?

Good point, `blas` and `lapack` folders should be in he `external` directory.

Nick, can you explain why we need blas_interface.F90 and lapack_interface.F90? Is it not possible to call F77 routines in a F90 code?

**Comment by amontoison** [comment]
Nick, it seems that I don't use the correct syntax to include the Fortran files.
I want to replace `blas.f` by `galahad_blas.F90` and its content is:
```fortran
! THIS VERSION: GALAHAD 5.0 - 2023-05-18 AT 14:15 GMT.

include "v3.11/snrm2.f90"
include "v3.11/dnrm2.f90"

include "v3.11/srotg.f90"
include "v3.11/drotg.f90"

include "v3.11/srot.f"
include "v3.11/drot.f"

include "v3.11/sswap.f"
include "v3.11/dswap.f"

include "v3.11/sscal.f"
include "v3.11/dscal.f"

include "v3.11/isamax.f"
include "v3.11/idamax.f"

include "v3.11/strsv.f"
include "v3.11/dtrsv.f"

include "v3.11/strsm.f"
include "v3.11/dtrsm.f"

include "v3.11/stbsv.f"
include "v3.11/dtbsv.f"

include "v3.11/sgemv.f"
include "v3.11/dgemv.f"

include "v3.11/sger.f"
include "v3.11/dger.f"
```
`v3.11` is the folder with all BLAS routines provided by reference LAPACK 3.11.0.
I have the following error when I compile
`../src/external/blas/galahad_blas.F90:3: Error: Can't open included file 'v3.11/snrm2.f90'`.

**Comment by nimgould** [comment]
Maybe it needs a full path? That would make it non portable ...

The blas_interface.F90 and lapack_interface.F90 packages are simply so that one
can call the routines by a generic name (eig, axpy not s/daxpy) and it will choose
the correct precision. Of courser one could do this using a preprocessor, but 
this is more natural (to me)

**Comment by amontoison** [comment]
> Maybe it needs a full path? That would make it non portable ...

I found the culprits.
I forgot `#` before the include statements and we can't include Fortran 77 and Fortran 90 files in the same files.

- meson.build
```meson
libgalahad_src += files('blas_interface.F90')

if not libblas.found()
  warning('building the reference BLAS version 3.11.0; consider providing an optimized BLAS library')
  libgalahad_src += files('galahad_blas1.f', 'galahad_blas2.F90')
endif
```

- galahad_blas1.f
```fortran
! THIS VERSION: GALAHAD 5.0 - 2023-05-18 AT 14:15 GMT.

#include "v3.11/srot.f"
#include "v3.11/drot.f"

#include "v3.11/sswap.f"
#include "v3.11/dswap.f"

#include "v3.11/sscal.f"
#include "v3.11/dscal.f"

#include "v3.11/isamax.f"
#include "v3.11/idamax.f"

#include "v3.11/strsv.f"
#include "v3.11/dtrsv.f"

#include "v3.11/strsm.f"
#include "v3.11/dtrsm.f"

#include "v3.11/stbsv.f"
#include "v3.11/dtbsv.f"

#include "v3.11/sgemv.f"
#include "v3.11/dgemv.f"

#include "v3.11/sger.f"
#include "v3.11/dger.f"
```

- galahad_blas2.F90
```fortran
! THIS VERSION: GALAHAD 5.0 - 2023-05-18 AT 14:15 GMT.

#include "v3.11/snrm2.f90"
#include "v3.11/dnrm2.f90"

#include "v3.11/srotg.f90"
#include "v3.11/drotg.f90"
```

- v3.11
Folder with all files provided by reference BLAS. It will easy to update now.

**Comment by amontoison** [comment]
> No, the fortran statement is include without a # , I think you must be using some other preprocessor. It seems that any files included must be in the same directory, the current directory or somewhere specified by the -I flag.

Thanks! I find a way to compile GALAHAD with updated BLAS / LAPACK routines.
I opened #127.

> This is all too complicated for something that already works. I suggest we revert as I have never seen a blas/lpacak error (and most people will use tuned libraries anyway).

Nick, I found why we have errors on Apple paltforms. 
Meson uses the `libblas.dylib` and `liblapack.dylib` libraries provided by Apple but they are very old.
We should check the version of MacOS to link GALAHAD with our own BLAS /  LAPACK if the version of Mac is lower than 13.3 (they added the updated Apple Accelerate in this version).

**Pull request closed without merging**
