### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
@jfowkes 
Jari, I have the following error with Mac Intel:
```
icpc -Ilibgalahad_single.dylib.p -I. -I.. -Iinclude -I../include -I../src/dum/include -Isrc/ampl -I../src/ampl -std=c++11 -O0 -g -traceback -diag-disable=10441 -qopenmp -DSPRAL_NO_SCHED_GETCPU -DSPRAL_NO_HWLOC -DGALAHAD_SINGLE -DSPRAL_SINGLE -DGALAHAD_BLAS -DGALAHAD_LAPACK -DDUMMY_SMUMPS -DDUMMY_MKL_PARDISO -DDUMMY_PARDISO -DDUMMY_PASTIXF -DDUMMY_SPMF -DDUMMY_WSMP -DDUMMY_MPI -DDUMMY_HSL -MD -MQ libgalahad_single.dylib.p/src_spral_omp.cxx.o -MF libgalahad_single.dylib.p/src_spral_omp.cxx.o.d -o libgalahad_single.dylib.p/src_spral_omp.cxx.o -c ../src/spral/omp.cxx
../src/spral/omp.cxx(11): catastrophic error: cannot open source file "../src/spral/omp.cxx"
  #include <cstdio>
                   ^

compilation aborted for ../src/spral/omp.cxx (code 4)
```
Does Apple removed some headers in the new version of Mac?

**Comment by jfowkes** [comment]
@amontoison it's looking for `omp.cxx`, have you installed OpenMP? `brew install openmp` should do it.

**Comment by amontoison** [comment]
> @amontoison it's looking for `omp.cxx`, have you installed OpenMP? `brew install openmp` should do it.

@jfowkes You quickly read the error message.
`omp.cxx` is in GALAHAD (`src/spral/omp.cxx`).
The compiler is just unable to find this header:
https://github.com/ralna/GALAHAD/blob/master/src/spral/omp.cxx#L11

**Comment by jfowkes** [comment]
@amontoison sorry too early in the morning, you are right! That is bizarre though as there's no way macOS would have removed the C header file that defines `printf`!! Most likely the C headers have moved again in the Xcode SDK (Apple keep moving them and it's really annoying). Is there an upstream Meson bug report about this somewhere?

**Comment by nimgould** [comment]
Alexis, while we have your attention, any idea why the setup on windows gcc

 https://github.com/ralna/GALAHAD/actions/runs/8881514809/job/24384048544

gives

Run CSTD="c99"
72
The Meson build system
73
Version: 1.4.0
74
Source dir: D:\a\GALAHAD\GALAHAD
75
Build dir: D:\a\GALAHAD\GALAHAD\builddir
76
Build type: native build
77
Project name: GALAHAD
78
Project version: 4.3.0
79
80
meson.build:1:0: ERROR: Compiler gfortran cannot compile programs.

?

I have no idea what this means, it downloaded gfortran

**Comment by jfowkes** [comment]
@amontoison as a quick fix you can just remove line 11 as `<cstdio>` is not actually used in that file (no printing happens).

**Comment by amontoison** [comment]
Ok, let's do that.

I checked with Google and found that:
https://apple.stackexchange.com/questions/458062/unable-to-find-include-file-on-newly-updated-macosc-c

Apple broke everything recently...

**Comment by jfowkes** [comment]
> Alexis, while we have your attention, any idea why the setup on windows gcc
> 
> https://github.com/ralna/GALAHAD/actions/runs/8881514809/job/24384048544
> 
> gives
> 
> Run CSTD="c99" 72 The Meson build system 73 Version: 1.4.0 74 Source dir: D:\a\GALAHAD\GALAHAD 75 Build dir: D:\a\GALAHAD\GALAHAD\builddir 76 Build type: native build 77 Project name: GALAHAD 78 Project version: 4.3.0 79 80 meson.build:1:0: ERROR: Compiler gfortran cannot compile programs.
> 
> ?
> 
> I have no idea what this means, it downloaded gfortran

@nimgould I suspect it probably doesn't like the linker option that we added to gfortran...

**Comment by amontoison** [comment]
@jfowkes 
```
icpc -Ilibgalahad_single.dylib.p -I. -I.. -Iinclude -I../include -I../src/dum/include -Isrc/ampl -I../src/ampl -std=c++11 -O0 -g -traceback -diag-disable=10441 -qopenmp -DSPRAL_NO_SCHED_GETCPU -DSPRAL_NO_HWLOC -DGALAHAD_SINGLE -DSPRAL_SINGLE -DGALAHAD_BLAS -DGALAHAD_LAPACK -DDUMMY_SMUMPS -DDUMMY_MKL_PARDISO -DDUMMY_PARDISO -DDUMMY_PASTIXF -DDUMMY_SPMF -DDUMMY_WSMP -DDUMMY_MPI -DDUMMY_HSL -DINTEGER_64 -MD -MQ libgalahad_single.dylib.p/src_spral_guess_topology.cxx.o -MF libgalahad_single.dylib.p/src_spral_guess_topology.cxx.o.d -o libgalahad_single.dylib.p/src_spral_guess_topology.cxx.o -c ../src/spral/guess_topology.cxx
In file included from ../src/spral/guess_topology.cxx(20):
../include/spral_compat.hxx(11): catastrophic error: cannot open source file "../include/spral_compat.hxx"
  #include <cstdint>
                    ^
```
😭

**Comment by jfowkes** [comment]
@amontoison guess we should open an upstream Meson bug report? C headers are pretty basic and Xcode is installed in the `macos-13` runner image as per:
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md

**Comment by amontoison** [comment]
> Alexis, while we have your attention, any idea why the setup on windows gcc
> 
> https://github.com/ralna/GALAHAD/actions/runs/8881514809/job/24384048544
> 
> gives
> 
> Run CSTD="c99" 72 The Meson build system 73 Version: 1.4.0 74 Source dir: D:\a\GALAHAD\GALAHAD 75 Build dir: D:\a\GALAHAD\GALAHAD\builddir 76 Build type: native build 77 Project name: GALAHAD 78 Project version: 4.3.0 79 80 meson.build:1:0: ERROR: Compiler gfortran cannot compile programs.
> 
> ?
> 
> I have no idea what this means, it downloaded gfortran

@nimgould 
I fix CI on `master` with this pull request and after I will rebase the other branch `galahad-nick`.
It could fix the your issue on Windows.
I will go to bed after!

**Comment by amontoison** [comment]
> Having said that, the old Intel compilers are unsupported on macOS anyway and Intel has no plans to support Macs.

And we can't compile SPRAL with these compilers on Mac...
I removed them, too painful to maintain.

**Comment by jfowkes** [comment]
> > Having said that, the old Intel compilers are unsupported on macOS anyway and Intel has no plans to support Macs.
> 
> And we can't compile SPRAL with these compilers on Mac... I removed them, too painful to maintain.

Agreed it's the correct decision, there's no point trying to support unsupported software.

**Comment by amontoison** [comment]
Ok, great!
Except a minor error in 64-bit integer build on Windows, all tests passed.
```
288/403 GALAHAD:dgo+single+C / dgot_c_single                             FAIL            0.12s   exit status 32
>>> UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 MALLOC_PERTURB_=26 D:\a\GALAHAD\GALAHAD\builddir\dgot_c_single.exe
```

**Comment by amontoison** [comment]
@nimgould I rebased the branch `galahad5-nick`.
You need to do a `git pull`.
If you have any issue with `git` like conflicts, I created a branch `galahad5-alexis` as a plan B for you.

**Comment by amontoison** [comment]
@nimgould @jfowkes 
r_2329045_c5v7p

**Pull request merged**
