### PR TITLE
Compile GALAHAD with reference BLAS and LAPACK

### PR DESCRIPTION
**Pull request by amontoison**
Nick, I found the subset of BLAS and LAPACK files that we need here in GALAHAD.
We should keep the list somewhere if one day we want to regenerate the source files in `src/lapack`.
I will use this PR to check that we don't mix single / double calls in GALAHAD routines. 

- BLAS
```fortran
include "xerbla.f"
include "lsame.f"

#ifdef GALAHAD_SINGLE
     include "srot.f"
     include "sswap.f"
     include "sscal.f"
     include "isamax.f"
     include "strsv.f"
     include "strsm.f"
     include "strmm.f"
     include "stbsv.f"
     include "sgemv.f"
     include "sgemm.f"
     include "sger.f"
     include "ssyrk.f"
     include "scopy.f"
     include "saxpy.f"
     include "ssyr.f"
     include "sdot.f"
     include "ssymv.f"
     include "ssymm.f"
     include "ssyr2.f"
     include "ssyr2k.f"
     include "strmv.f"
#else
     include "drot.f"
     include "dswap.f"
     include "dscal.f"
     include "idamax.f"
     include "dtrsv.f"
     include "dtrsm.f"
     include "dtrmm.f"
     include "dtbsv.f"
     include "dgemv.f"
     include "dgemm.f"
     include "dger.f"
     include "dsyrk.f"
     include "dcopy.f"
     include "daxpy.f"
     include "dsyr.f"
     include "ddot.f"
     include "dsymv.f"
     include "dsymm.f"
     include "dsyr2.f"
     include "dsyr2k.f"
     include "dtrmv.f"
#endif
```
```fortran
#ifdef GALAHAD_SINGLE
     include "snrm2.f90"
     include "srotg.f90"
#else
     include "dnrm2.f90"
     include "drotg.f90"
#endif
```

- LAPACK
```fortran
include "ilaenv.f"
include "iparmq.f"
include "iladlr.f"
include "ilaslc.f"
include "ilaslr.f"
include "iladlc.f"

#ifdef GALAHAD_SINGLE
     include "slaic1.f"
     include "stzrzf.f"
     include "sgeqrf.f"
     include "sgetrf.f"
     include "sgetrf2.f"
     include "sgetrs.f"
     include "sgels.f"
     include "sgelsy.f"
     include "sgelss.f"
     include "sgelsd.f"
     include "sgesvd.f"
     include "spttrf.f"
     include "spotrf.f"
     include "spotrf2.f"
     include "spotrs.f"
     include "ssytrf.f"
     include "ssytrs.f"
     include "spbtrf.f"
     include "spbtf2.f"
     include "spbtrs.f"
     include "ssyev.f"
     include "ssygv.f"
     include "shseqr.f"
     include "ssterf.f"
     include "slaev2.f"
     include "ssygst.f"
     include "slasyf.f"
     include "ssytf2.f"
     include "spotf2.f"
     include "slaqr0.f"
     include "slahqr.f"
     include "sisnan.f"
     include "slaisnan.f"
     include "slacpy.f"
     include "slaset.f"
     include "sbdsqr.f"
     include "slascl.f"
     include "sorgbr.f"
     include "sormbr.f"
     include "slaqr1.f"
     include "slaqr2.f"
     include "slaqr3.f"
     include "slaqr4.f"
     include "slaqr5.f"
     include "slanv2.f"
     include "slabad.f"
     include "sorgqr.f"
     include "slamch.f"
     include "sgelqf.f"
     include "sorglq.f"
     include "slange.f"
     include "sgebrd.f"
     include "slalsd.f"
     include "sormlq.f"
     include "sormqr.f"
     include "srscl.f"
     include "sormrz.f"
     include "strtrs.f"
     include "slaswp.f"
     include "sgeqp3.f"
     include "sormr3.f"
     include "slaqp2.f"
     include "slarzt.f"
     include "slarf.f"
     include "slarzb.f"
     include "slarfg.f"
     include "slapy2.f"
     include "slarz.f"
     include "slaqps.f"
     include "slatrz.f"
     include "slarfb.f"
     include "slarft.f"
     include "sorml2.f"
     include "sorm2r.f"
     include "slasrt.f"
     include "slasdq.f"
     include "slasda.f"
     include "slasr.f"
     include "slalsa.f"
     include "sgehrd.f"
     include "sormhr.f"
     include "strexc.f"
     include "slahr2.f"
     include "slansy.f"
     include "ssteqr.f"
     include "sgelq2.f"
     include "sorg2r.f"
     include "sgeqr2.f"
     include "sorgl2.f"
     include "slals0.f"
     include "slamrg.f"
     include "sgebd2.f"
     include "slasdt.f"
     include "slabrd.f"
     include "slasd4.f"
     include "slasd5.f"
     include "slasd6.f"
     include "slasd7.f"
     include "slasd8.f"
     include "slaed6.f"
     include "slanst.f"
     include "slas2.f"
     include "slae2.f"
     include "slasq1.f"
     include "slasq2.f"
     include "slasq3.f"
     include "slasq4.f"
     include "slasq5.f"
     include "slasq6.f"
     include "ssygs2.f"
     include "slasv2.f"
     include "slaexc.f"
     include "sorgtr.f"
     include "slarfx.f"
     include "sgehd2.f"
     include "slasy2.f"
     include "ssytrd.f"
     include "ssytd2.f"
     include "sorgql.f"
     include "slatrd.f"
     include "sorg2l.f"
#else
     include "dlaic1.f"
     include "dtzrzf.f"
     include "dgeqrf.f"
     include "dgetrf.f"
     include "dgetrf2.f"
     include "dgetrs.f"
     include "dgels.f"
     include "dgelsy.f"
     include "dgelss.f"
     include "dgelsd.f"
     include "dgesvd.f"
     include "dpttrf.f"
     include "dpotrf.f"
     include "dpotrf2.f"
     include "dpotrs.f"
     include "dsytrf.f"
     include "dsytrs.f"
     include "dpbtrf.f"
     include "dpbtf2.f"
     include "dpbtrs.f"
     include "dsyev.f"
     include "dsygv.f"
     include "dhseqr.f"
     include "dsterf.f"
     include "dlaev2.f"
     include "dsygst.f"
     include "dlasyf.f"
     include "dsytf2.f"
     include "dpotf2.f"
     include "dlaqr0.f"
     include "dlahqr.f"
     include "disnan.f"
     include "dlaisnan.f"
     include "dlacpy.f"
     include "dlaset.f"
     include "dbdsqr.f"
     include "dlascl.f"
     include "dorgbr.f"
     include "dormbr.f"
     include "dlaqr1.f"
     include "dlaqr2.f"
     include "dlaqr3.f"
     include "dlaqr4.f"
     include "dlaqr5.f"
     include "dlanv2.f"
     include "dlabad.f"
     include "dorgqr.f"
     include "dlamch.f"
     include "dgelqf.f"
     include "dorglq.f"
     include "dlange.f"
     include "dgebrd.f"
     include "dlalsd.f"
     include "dormlq.f"
     include "dormqr.f"
     include "drscl.f"
     include "dormrz.f"
     include "dtrtrs.f"
     include "dlaswp.f"
     include "dgeqp3.f"
     include "dormr3.f"
     include "dlaqp2.f"
     include "dlarzt.f"
     include "dlarf.f"
     include "dlarzb.f"
     include "dlarfg.f"
     include "dlapy2.f"
     include "dlarz.f"
     include "dlaqps.f"
     include "dlatrz.f"
     include "dlarfb.f"
     include "dlarft.f"
     include "dorml2.f"
     include "dorm2r.f"
     include "dlasrt.f"
     include "dlasdq.f"
     include "dlasda.f"
     include "dlasr.f"
     include "dlalsa.f"
     include "dgehrd.f"
     include "dormhr.f"
     include "dtrexc.f"
     include "dlahr2.f"
     include "dlansy.f"
     include "dsteqr.f"
     include "dgelq2.f"
     include "dorg2r.f"
     include "dgeqr2.f"
     include "dorgl2.f"
     include "dlals0.f"
     include "dlamrg.f"
     include "dgebd2.f"
     include "dlasdt.f"
     include "dlabrd.f"
     include "dlasd4.f"
     include "dlasd5.f"
     include "dlasd6.f"
     include "dlasd7.f"
     include "dlasd8.f"
     include "dlaed6.f"
     include "dlanst.f"
     include "dlas2.f"
     include "dlae2.f"
     include "dlasq1.f"
     include "dlasq2.f"
     include "dlasq3.f"
     include "dlasq4.f"
     include "dlasq5.f"
     include "dlasq6.f"
     include "dsygs2.f"
     include "dlasv2.f"
     include "dlaexc.f"
     include "dorgtr.f"
     include "dlarfx.f"
     include "dgehd2.f"
     include "dlasy2.f"
     include "dsytrd.f"
     include "dsytd2.f"
     include "dorgql.f"
     include "dlatrd.f"
     include "dorg2l.f"
#endif
```

```fortran
include "la_constants.f90"
include "la_xisnan.F90"

#ifdef GALAHAD_SINGLE
     include "slassq.f90"
     include "slartg.f90"
#else
     include "dlassq.f90"
     include "dlartg.f90"
#endif
```

### CODE REVIEW

**Comment by amontoison** [comment]
Nick, I found the collection of BLAS and LAPACK files that we need here in GALAHAD.
We should keep the list somewhere if one day we want to regenerate the source files in `src/lapack`.
I will use this PR to check that we don't mix single / double calls in GALAHAD routines
. 
- BLAS
```fortran
include "xerbla.f"
include "lsame.f"
include "srot.f"
include "drot.f"
include "sswap.f"
include "dswap.f"
include "sscal.f"
include "dscal.f"
include "isamax.f"
include "idamax.f"
include "strsv.f"
include "dtrsv.f"
include "strsm.f"
include "dtrsm.f"
include "strmm.f"
include "dtrmm.f"
include "stbsv.f"
include "dtbsv.f"
include "sgemv.f"
include "dgemv.f"
include "sgemm.f"
include "dgemm.f"
include "sger.f"
include "dger.f"
include "ssyrk.f"
include "dsyrk.f"
include "scopy.f"
include "dcopy.f"
include "saxpy.f"
include "daxpy.f"
include "ssyr.f"
include "dsyr.f"
include "sdot.f"
include "ddot.f"
include "ssymv.f"
include "dsymv.f"
include "ssymm.f"
include "dsymm.f"
include "ssyr2.f"
include "dsyr2.f"
include "ssyr2k.f"
include "dsyr2k.f"
include "strmv.f"
include "dtrmv.f"
```
```fortran
include "snrm2.f90"
include "dnrm2.f90"
include "srotg.f90"
include "drotg.f90"
```

- LAPACK
```fortran
include "ilaenv.f"
include "iparmq.f"
include "iladlr.f"
include "ilaslc.f"
include "ilaslr.f"
include "iladlc.f"
include "slaic1.f"
include "dlaic1.f"
include "stzrzf.f"
include "dtzrzf.f"
include "sgeqrf.f"
include "dgeqrf.f"
include "sgetrf.f"
include "dgetrf.f"
include "sgetrf2.f"
include "dgetrf2.f"
include "sgetrs.f"
include "dgetrs.f"
include "sgels.f"
include "dgels.f"
include "sgelsy.f"
include "dgelsy.f"
include "sgelss.f"
include "dgelss.f"
include "sgelsd.f"
include "dgelsd.f"
include "sgesvd.f"
include "dgesvd.f"
include "spttrf.f"
include "dpttrf.f"
include "spotrf.f"
include "dpotrf.f"
include "spotrf2.f"
include "dpotrf2.f"
include "spotrs.f"
include "dpotrs.f"
include "ssytrf.f"
include "dsytrf.f"
include "ssytrs.f"
include "dsytrs.f"
include "spbtrf.f"
include "dpbtrf.f"
include "spbtf2.f"
include "dpbtf2.f"
include "spbtrs.f"
include "dpbtrs.f"
include "ssyev.f"
include "dsyev.f"
include "ssygv.f"
include "dsygv.f"
include "shseqr.f"
include "dhseqr.f"
include "ssterf.f"
include "dsterf.f"
include "slaev2.f"
include "dlaev2.f"
include "ssygst.f"
include "dsygst.f"
include "slasyf.f"
include "dlasyf.f"
include "ssytf2.f"
include "dsytf2.f"
include "spotf2.f"
include "dpotf2.f"
include "slaqr0.f"
include "dlaqr0.f"
include "slahqr.f"
include "dlahqr.f"
include "sisnan.f"
include "disnan.f"
include "slaisnan.f"
include "dlaisnan.f"
include "slacpy.f"
include "dlacpy.f"
include "slaset.f"
include "dlaset.f"
include "sbdsqr.f"
include "dbdsqr.f"
include "slascl.f"
include "dlascl.f"
include "sorgbr.f"
include "dorgbr.f"
include "sormbr.f"
include "dormbr.f"
include "slaqr1.f"
include "dlaqr1.f"
include "slaqr2.f"
include "dlaqr2.f"
include "slaqr3.f"
include "dlaqr3.f"
include "slaqr4.f"
include "dlaqr4.f"
include "slaqr5.f"
include "dlaqr5.f"
include "slanv2.f"
include "dlanv2.f"
include "slabad.f"
include "dlabad.f"
include "sorgqr.f"
include "dorgqr.f"
include "slamch.f"
include "dlamch.f"
include "sgelqf.f"
include "dgelqf.f"
include "sorglq.f"
include "dorglq.f"
include "slange.f"
include "dlange.f"
include "sgebrd.f"
include "dgebrd.f"
include "slalsd.f"
include "dlalsd.f"
include "sormlq.f"
include "dormlq.f"
include "sormqr.f"
include "dormqr.f"
include "srscl.f"
include "drscl.f"
include "sormrz.f"
include "dormrz.f"
include "strtrs.f"
include "dtrtrs.f"
include "slaswp.f"
include "dlaswp.f"
include "sgeqp3.f"
include "dgeqp3.f"
include "sormr3.f"
include "dormr3.f"
include "slaqp2.f"
include "dlaqp2.f"
include "slarzt.f"
include "dlarzt.f"
include "slarf.f"
include "dlarf.f"
include "slarzb.f"
include "dlarzb.f"
include "slarfg.f"
include "dlarfg.f"
include "slapy2.f"
include "dlapy2.f"
include "slarz.f"
include "dlarz.f"
include "slaqps.f"
include "dlaqps.f"
include "slatrz.f"
include "dlatrz.f"
include "slarfb.f"
include "dlarfb.f"
include "slarft.f"
include "dlarft.f"
include "sorml2.f"
include "dorml2.f"
include "sorm2r.f"
include "dorm2r.f"
include "slasrt.f"
include "dlasrt.f"
include "slasdq.f"
include "dlasdq.f"
include "slasda.f"
include "dlasda.f"
include "slasr.f"
include "dlasr.f"
include "slalsa.f"
include "dlalsa.f"
include "sgehrd.f"
include "dgehrd.f"
include "sormhr.f"
include "dormhr.f"
include "strexc.f"
include "dtrexc.f"
include "slahr2.f"
include "dlahr2.f"
include "slansy.f"
include "dlansy.f"
include "ssteqr.f"
include "dsteqr.f"
include "sgelq2.f"
include "dgelq2.f"
include "sorg2r.f"
include "dorg2r.f"
include "sgeqr2.f"
include "dgeqr2.f"
include "sorgl2.f"
include "dorgl2.f"
include "slals0.f"
include "dlals0.f"
include "slamrg.f"
include "dlamrg.f"
include "sgebd2.f"
include "dgebd2.f"
include "slasdt.f"
include "dlasdt.f"
include "slabrd.f"
include "dlabrd.f"
include "slasd4.f"
include "dlasd4.f"
include "slasd5.f"
include "dlasd5.f"
include "slasd6.f"
include "dlasd6.f"
include "slasd7.f"
include "dlasd7.f"
include "slasd8.f"
include "dlasd8.f"
include "slaed6.f"
include "dlaed6.f"
include "slanst.f"
include "dlanst.f"
include "slas2.f"
include "dlas2.f"
include "slae2.f"
include "dlae2.f"
include "slasq1.f"
include "dlasq1.f"
include "slasq2.f"
include "dlasq2.f"
include "slasq3.f"
include "dlasq3.f"
include "slasq4.f"
include "dlasq4.f"
include "slasq5.f"
include "dlasq5.f"
include "slasq6.f"
include "dlasq6.f"
include "ssygs2.f"
include "dsygs2.f"
include "slasv2.f"
include "dlasv2.f"
include "slaexc.f"
include "dlaexc.f"
include "sorgtr.f"
include "dorgtr.f"
include "slarfx.f"
include "dlarfx.f"
include "sgehd2.f"
include "dgehd2.f"
include "slasy2.f"
include "dlasy2.f"
include "ssytrd.f"
include "dsytrd.f"
include "ssytd2.f"
include "dsytd2.f"
include "sorgql.f"
include "dorgql.f"
include "slatrd.f"
include "dlatrd.f"
include "sorg2l.f"
include "dorg2l.f"
```

```fortran
include "la_constants.f90"
include "la_xisnan.F90"
include "slartg.f90"
include "dlartg.f90"
include "slassq.f90"
include "dlassq.f90"
```

**Comment by nimgould** [comment]
Thanks, it is good to have these lists. 

Perhaps it is time for me to regenerate the entire blas and lapack combined files with these? One small complication is that the .f files are in fixed format, while the .f90 are in free (and one of the later requires preprocessing). This can be worked around by having two combined files blas77.f and blas90.f90 that are together compiled in galahad_blas.a/so . Or maybe you are right, we can simply use the fortran includes; I presume that all the files will occur in the same directory? It may be worth having two directories one for blas and one for lapack. There is a minor problem in that currently a temporary copy of the file is made to the object directory before the compilation ... and if so, the files to be included are left behind. I can code around this

The .F90 file relies on USE_IEEE_INTRINSIC and USE_ISNAN, but will work without either

**Comment by nimgould** [comment]
I'll work on this later, once I have fixed and tested the metis issues

**Comment by amontoison** [comment]
Yes, we can do that later. I'm just glad that we solved the errors on Mac!

**Comment by amontoison** [comment]
@nimgould 
I found that `ssids/cpu_solve.F90` always calls double precision version of `gemv`, `gemm`, `trsv` and `trsm`.
It could an issue if we compile `ssids` in single precision.
We should probably use `blas_interface.F90`.
I implemented the missing interface for `GEMM`:
```fortran
!  matrix-matrix product

      INTERFACE GEMM

        SUBROUTINE SGEMM(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
          REAL :: ALPHA, BETA
          INTEGER :: K, LDA, LDB, LDC, M, N
          CHARACTER ( LEN = 1 ) :: TRANSA, TRANSB
          REAL :: A(LDA,*), B(LDB,*), C(LDC,*)
        END SUBROUTINE SGEMM

        SUBROUTINE DGEMM(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
          DOUBLE PRECISION :: ALPHA, BETA
          INTEGER :: K, LDA, LDB, LDC, M, N
          CHARACTER ( LEN = 1 ) :: TRANSA, TRANSB
          DOUBLE PRECISION :: A(LDA,*), B(LDB,*), C(LDC,*)
        END SUBROUTINE DGEMM

      END INTERFACE GEMM
```

**Comment by amontoison** [comment]
> I'll work on this later, once I have fixed and tested the metis issues

I propose to discuss about it when I will come in July, it will be easier to synchronize the update of Meson / `makemaster` build systems. The current version is working fine.

**Comment by nimgould** [comment]
Well spotted!! I have no idea why I missed those

**Comment by nimgould** [comment]
I made the changes here; of course this routine is only used if the gpu version of ssids is compiled (which it isn't by default).

We (Group) are getting an Mac M2 next week so should be able to test OSX things locally.

Still getting the 
libgalahad_single.so.p/../include/galahad_*.h(786): warning #5117: Bad # preprocessor line
3171
# 4 "libgalahad_single.so.p/../src/wcp/C/*_ciface.F90" 2 
everywhere for ubuntu-latest intel latest via actions, and a compiler bug for sids_wrappers.cxx (with a report to Intel message). It is fine running locally

**Comment by nimgould** [comment]
And another one that says
ninja: build stopped: subcommand failed.
2812
INFO: autodetecting backend as ninja
2813
INFO: calculating backend command to run: /Users/runner/hostedtoolcache/Python/3.11.3/x64/bin/ninja -C /Users/runner/work/GALAHAD/GALAHAD/builddir
No idea why, that is all I see. Details from
https://github.com/ralna/GALAHAD/actions/runs/5031615575

**Comment by nimgould** [comment]
Damn. the BLAS calls in cpu_solve.F90  are breaking the standard, and passing 2D arrays as 1D. Thus we can't use the generic interface.  Instead, we will have to use the C preprocessor.  Not a big deal, but more coding.

**Comment by nimgould** [comment]
Now fixed. How annoying!!

**Comment by amontoison** [comment]
> I made the changes here; of course this routine is only used if the gpu version of ssids is compiled (which it isn't by default).
> 
> We (Group) are getting an Mac M2 next week so should be able to test OSX things locally.

Great! :tada: 

> Still getting the
> 
> ```
> libgalahad_single.so.p/../include/galahad_*.h(786): warning #5117: Bad # preprocessor line
> 3171
> # 4 "libgalahad_single.so.p/../src/wcp/C/*_ciface.F90" 2 
> ```
> 
> everywhere for ubuntu-latest intel latest via actions, and a compiler bug for sids_wrappers.cxx (with a report to Intel message). It is fine running locally

I removed the warnings related to depreceated `icc` / `icpc` compilers and fixed the "Bad # preprocessor line" in #129 but I don't know how to solve the compile bug with C++ files. I give the command used by Meson, maybe you will be able to reproduce the issue locally.

**Pull request closed without merging**
