### PR TITLE
[CI] Automatically precompile GALAHAD when a new release is tagged

### PR DESCRIPTION
**Pull request by amontoison**
@nimgould 
This pull request adds a script that automatically creates a new GitHub release with precompiled binaries for your convenience.
This means that you only need to tag the latest commit on the branch `master` to trigger the action.
```shell
git checkout master
git tag <tagname>
git push origin --tags
```
Note: `<tagname>` must have a `'v'` as the first character, such as `v1.0.0` or `v2024.01.18`.

@jfowkes, could you please explain what you did with SPRAL as an example to Nick when you both are at RAL?

### CODE REVIEW

**Comment by jfowkes** [comment]
@amontoison will do, but we should probably make sure that the binaries actually compile first...

**Comment by nimgould** [comment]
I agree, slightly premature particularly as much is adapting to _64

**Comment by amontoison** [comment]
Jari, it's almost a copy-paste of the `build_tarballs.jl` that I use with Yggdrasil.

**Comment by amontoison** [comment]
@jfowkes @nimgould 
Tested on my fork: https://github.com/amontoison/GALAHAD/releases/tag/v5.0.0 :tada:

**Pull request merged**
