### PR TITLE
Comment #pragma omp cancellation point taskgroup in C++ code of SSIDS

### PR DESCRIPTION
**Pull request by amontoison**
@jfowkes @nimgould 
By commenting the lines with `#pragma omp cancellation point taskgroup` in SSIDS, I fixed the compilation with Intel compilers.

### CODE REVIEW

**Comment by nimgould** [comment]
Great. This only comes up as a warning here, but I presume it is marked as an error in your tests. Since I have no idea what Jonathan Hogg had in mind, best to avoid the issue

**Comment by nimgould** [comment]
The warnings have now gone, but as I said, the old code still worked here with the warnings

**Comment by nimgould** [comment]
aside for this compiler failure, ifx is also not fully fortran-2017 compliant, and 
in particular doesn't support some of the standard iso C interface changes that
we need. Thus, for the time being, we should use ifort/icx not ifx/icx, the icx part
is mature.

**Comment by jfowkes** [comment]
Although icx is still not available on macOS so there we must use ifort/icc (Intel still ships icc for macOS for now).

**Comment by jfowkes** [comment]
Intel compiler download pages (select compilers on left menu):
https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html

**Pull request merged**
